from __future__ import annotations

from datetime import datetime
from typing import Protocol, Self

from app.core.content.events.application.dto import EventDetails
from app.core.content.events.domain.category import EventCategory
from app.core.content.events.domain.event import Event


class EventRepository(Protocol):
    def get(self, event_id: int) -> Event | None: ...
    def get_many(self, event_ids: list[int]) -> list[Event]: ...
    def get_by_match(self, match_id: int) -> Event | None: ...
    def save(self, event: Event) -> Event: ...
    def delete(self, event: Event) -> None: ...


class CategoryRepository(Protocol):
    def get(self, category_id: int) -> EventCategory | None: ...
    def get_by_slug(self, slug: str) -> EventCategory | None: ...
    def save(self, category: EventCategory) -> EventCategory: ...


class EventUnitOfWork(Protocol):
    """One transaction for category/event writes, including bulk operations."""

    events: EventRepository
    categories: CategoryRepository

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...


class EventReader(Protocol):
    def categories(self, *, public: bool = False) -> list[EventCategory]: ...
    def years(self) -> list[int]: ...
    def get(self, event_id: int) -> EventDetails | None: ...
    def get_many(self, event_ids: list[int]) -> list[EventDetails]: ...
    def list(
        self, *, year: int | None = None, category_ids: list[int] | None = None
    ) -> list[EventDetails]: ...
    def public_list(
        self,
        *,
        starts_from: datetime,
        starts_until: datetime,
        category_ids: list[int] | None = None,
    ) -> list[EventDetails]: ...
