from typing import Protocol, Self

from app.core.content.articles.application.dto import (
    GeneratedMatchReport,
    MatchReportData,
)
from app.core.content.articles.domain.article import Article


class ArticleRepository(Protocol):
    def slug_exists(self, slug: str) -> bool: ...

    def save(self, article: Article) -> Article: ...
    def get(self, article_id: int, *, for_update: bool = False) -> Article | None: ...
    def lock_generation(self, team_match_id: int) -> None: ...
    def find_match_report(self, key: str, event_id: int | None) -> Article | None: ...


class ArticleUnitOfWork(Protocol):
    articles: ArticleRepository

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...


class MatchReportReader(Protocol):
    def read(self, team_match_id: int) -> MatchReportData: ...


class MatchReportGenerator(Protocol):
    def generate(self, data: MatchReportData) -> GeneratedMatchReport: ...


class ArticleAuthors(Protocol):
    def system_id(self) -> int: ...
    def ensure_editor(self, user_id: int) -> None: ...
