from datetime import datetime
from typing import Protocol, Self

from app.core.competition.application.events import TeamMatchResultsImported
from app.core.competition.application.sync.imports import (
    GroupReference,
    ImportedPlayer,
    MeetingDetails,
    MeetingReference,
    Registration,
    ScheduleSnapshot,
    Standing,
)
from app.core.competition.domain.leagues import LeagueGroup
from app.core.competition.domain.matches import TeamMatch
from app.core.competition.domain.seasons import Season, SeasonKey
from app.core.competition.domain.teams import Team


class CompetitionRepository(Protocol):
    def match_ids(self, *, completed_only: bool = False) -> list[int]: ...

    def find_season(self, key: SeasonKey) -> Season | None: ...
    def save_season(self, season: Season) -> None: ...

    def find_group(self, season_id: int, external_id: int) -> LeagueGroup | None: ...
    def get_group(self, group_id: int) -> LeagueGroup | None: ...
    def save_group(self, group: LeagueGroup) -> None: ...

    def find_team(self, season_id: int, external_id: int) -> Team | None: ...
    def teams_in_group(self, group_id: int) -> list[Team]: ...
    def save_team(self, team: Team) -> None: ...

    def find_team_match(self, external_id: int) -> TeamMatch | None: ...
    def get_team_match(
        self, match_id: int, *, for_update: bool = False
    ) -> TeamMatch | None: ...
    def save_team_match(self, match: TeamMatch) -> None: ...


class CompetitionSource(Protocol):
    async def schedule(self, season: SeasonKey) -> ScheduleSnapshot: ...
    async def meeting(self, external_id: int) -> MeetingDetails: ...
    async def registrations(
        self, group: GroupReference
    ) -> tuple[Registration, ...]: ...
    async def standings(self, group: GroupReference) -> tuple[Standing, ...]: ...


class CompetitionReader(Protocol):
    def meeting(self, match_id: int) -> MeetingReference: ...
    def match_id(self, external_id: int) -> int: ...
    def group(self, group_id: int, *, require_team: bool = False) -> GroupReference: ...
    def season_id(self, season: SeasonKey) -> int | None: ...
    def group_ids(
        self, season_id: int | None = None, *, with_team: bool = False
    ) -> list[int]: ...
    def pending_match_ids(
        self, *, season_id: int | None = None, before: datetime | None = None
    ) -> list[int]: ...
    def has_standings(self, group_id: int) -> bool: ...


class ImportedPlayers(Protocol):
    def resolve(self, player: ImportedPlayer, *, update_names: bool = False) -> int: ...


class MatchEvents(Protocol):
    def synchronize(self, match_id: int) -> bool: ...


class CompetitionEventOutbox(Protocol):
    """Stage a message in the same transaction as the imported results."""

    def add(self, event: TeamMatchResultsImported) -> None: ...


class RegistrationReportReader(Protocol):
    def read(self) -> tuple[list[dict], list[dict]]: ...


class SyncUnitOfWork(Protocol):
    repository: CompetitionRepository
    players: ImportedPlayers
    events: MatchEvents
    outbox: CompetitionEventOutbox

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...
