"""adjust historical import fields

Revision ID: 57c109e656c8
Revises: 9258e60bfd1c
Create Date: 2026-08-23 02:25:40.328166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '57c109e656c8'
down_revision: Union[str, Sequence[str], None] = '9258e60bfd1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_match_notice',
    sa.Column('team_match_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team_match_id'], ['team_match.id'], ),
    sa.PrimaryKeyConstraint('team_match_id', 'code')
    )
    op.drop_table('teammatchnotice')
    op.alter_column('league_group', 'mytt_slug',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('team', 'team_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('team', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('team_match', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('team_match', 'original_scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('team_match', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('team_match', 'ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_match', 'ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('team_match', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('team_match', 'original_scheduled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('team_match', 'scheduled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('team', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('team', 'team_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('league_group', 'mytt_slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('teammatchnotice',
    sa.Column('team_match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_match_id'], ['team_match.id'], name=op.f('teammatchnotice_team_match_id_fkey')),
    sa.PrimaryKeyConstraint('team_match_id', 'code', name=op.f('teammatchnotice_pkey'))
    )
    op.drop_table('team_match_notice')
    # ### end Alembic commands ###
