"""add content models

Revision ID: 7db6ed6f7c03
Revises: 9467ae3d6b41
Create Date: 2026-08-28 15:40:01.676042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7db6ed6f7c03'
down_revision: Union[str, Sequence[str], None] = '9467ae3d6b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


event_status_enum = postgresql.ENUM(
    "PLANNED",
    "COMPLETED",
    "CANCELLED",
    "POSTPONED",
    name="event_status",
    create_type=False,
)
content_visibility_enum = postgresql.ENUM(
    "PUBLIC",
    "MEMBERS_ONLY",
    "HIDDEN",
    name="content_visibility",
    create_type=False,
)
article_status_enum = postgresql.ENUM(
    "DRAFT",
    "IN_REVIEW",
    "PUBLISHED",
    "ARCHIVED",
    name="article_status",
    create_type=False,
)
article_type_enum = postgresql.ENUM(
    "NEWS",
    "MATCH_REPORT",
    "EVENT_REPORT",
    "ANNUAL_REPORT",
    "ANNOUNCEMENT",
    name="article_type",
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    event_status_enum.create(bind, checkfirst=True)
    content_visibility_enum.create(bind, checkfirst=True)
    article_status_enum.create(bind, checkfirst=True)
    article_type_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_report_expected', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_category_slug'), 'event_category', ['slug'], unique=True)
    op.create_index(op.f('ix_event_category_sort_order'), 'event_category', ['sort_order'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_slug'), 'tag', ['slug'], unique=True)
    op.create_table('media_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photographer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_media_asset_uploaded_by_user_id'), 'media_asset', ['uploaded_by_user_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('team_match_id', sa.Integer(), nullable=True),
    sa.Column('status', event_status_enum, nullable=False),
    sa.Column('visibility', content_visibility_enum, nullable=False),
    sa.Column('report_expected', sa.Boolean(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ends_at IS NULL OR ends_at >= starts_at', name='ck_event_end_not_before_start'),
    sa.ForeignKeyConstraint(['category_id'], ['event_category.id'], ),
    sa.ForeignKeyConstraint(['team_match_id'], ['team_match.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_category_id'), 'event', ['category_id'], unique=False)
    op.create_index(op.f('ix_event_report_expected'), 'event', ['report_expected'], unique=False)
    op.create_index(op.f('ix_event_starts_at'), 'event', ['starts_at'], unique=False)
    op.create_index(op.f('ix_event_status'), 'event', ['status'], unique=False)
    op.create_index(op.f('ix_event_team_match_id'), 'event', ['team_match_id'], unique=True)
    op.create_index(op.f('ix_event_visibility'), 'event', ['visibility'], unique=False)
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('visibility', content_visibility_enum, nullable=False),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cover_image_id'], ['media_asset.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_created_by_user_id'), 'gallery', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_gallery_event_id'), 'gallery', ['event_id'], unique=True)
    op.create_index(op.f('ix_gallery_slug'), 'gallery', ['slug'], unique=True)
    op.create_index(op.f('ix_gallery_visibility'), 'gallery', ['visibility'], unique=False)
    op.create_table('article_tag',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_table('gallery_media',
    sa.Column('gallery_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('caption_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gallery_id', 'media_asset_id')
    )
    op.add_column('article', sa.Column('event_id', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=False))
    op.add_column('article', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('status', article_status_enum, nullable=False, server_default='DRAFT'))
    op.add_column('article', sa.Column('article_type', article_type_enum, nullable=False, server_default='NEWS'))
    op.add_column('article', sa.Column('visibility', content_visibility_enum, nullable=False, server_default='PUBLIC'))
    op.alter_column('article', 'published_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('article', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('article', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_article_article_type'), 'article', ['article_type'], unique=False)
    op.create_index(op.f('ix_article_author_id'), 'article', ['author_id'], unique=False)
    op.create_index(op.f('ix_article_event_id'), 'article', ['event_id'], unique=False)
    op.create_index(op.f('ix_article_slug'), 'article', ['slug'], unique=True)
    op.create_index(op.f('ix_article_status'), 'article', ['status'], unique=False)
    op.create_index(op.f('ix_article_visibility'), 'article', ['visibility'], unique=False)
    op.create_foreign_key('fk_article_author_id_user', 'article', 'user', ['author_id'], ['id'])
    op.create_foreign_key('fk_article_event_id_event', 'article', 'event', ['event_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_article_cover_image_id_media_asset', 'article', 'media_asset', ['cover_image_id'], ['id'], ondelete='SET NULL')
    op.alter_column('article', 'status', server_default=None)
    op.alter_column('article', 'article_type', server_default=None)
    op.alter_column('article', 'visibility', server_default=None)
    op.drop_column('article', 'image_url')
    op.drop_column('article', 'published')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False, server_default=sa.false()))
    op.add_column('article', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute("UPDATE article SET published = true WHERE status = 'PUBLISHED'")
    op.alter_column('article', 'published', server_default=None)
    op.drop_constraint('fk_article_cover_image_id_media_asset', 'article', type_='foreignkey')
    op.drop_constraint('fk_article_event_id_event', 'article', type_='foreignkey')
    op.drop_constraint('fk_article_author_id_user', 'article', type_='foreignkey')
    op.drop_index(op.f('ix_article_visibility'), table_name='article')
    op.drop_index(op.f('ix_article_status'), table_name='article')
    op.drop_index(op.f('ix_article_slug'), table_name='article')
    op.drop_index(op.f('ix_article_event_id'), table_name='article')
    op.drop_index(op.f('ix_article_author_id'), table_name='article')
    op.drop_index(op.f('ix_article_article_type'), table_name='article')
    op.alter_column('article', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('article', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('article', 'published_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('article', 'visibility')
    op.drop_column('article', 'article_type')
    op.drop_column('article', 'status')
    op.drop_column('article', 'cover_image_id')
    op.drop_column('article', 'author_id')
    op.drop_column('article', 'event_id')
    op.drop_table('gallery_media')
    op.drop_table('article_tag')
    op.drop_index(op.f('ix_gallery_visibility'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_slug'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_event_id'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_created_by_user_id'), table_name='gallery')
    op.drop_table('gallery')
    op.drop_index(op.f('ix_event_visibility'), table_name='event')
    op.drop_index(op.f('ix_event_team_match_id'), table_name='event')
    op.drop_index(op.f('ix_event_status'), table_name='event')
    op.drop_index(op.f('ix_event_starts_at'), table_name='event')
    op.drop_index(op.f('ix_event_report_expected'), table_name='event')
    op.drop_index(op.f('ix_event_category_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_media_asset_uploaded_by_user_id'), table_name='media_asset')
    op.drop_table('media_asset')
    op.drop_index(op.f('ix_tag_slug'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_event_category_sort_order'), table_name='event_category')
    op.drop_index(op.f('ix_event_category_slug'), table_name='event_category')
    op.drop_table('event_category')

    article_type_enum.drop(op.get_bind(), checkfirst=True)
    article_status_enum.drop(op.get_bind(), checkfirst=True)
    content_visibility_enum.drop(op.get_bind(), checkfirst=True)
    event_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
