"""add team match details imported at

Revision ID: 8c3384772b5f
Revises: 57c109e656c8
Create Date: 2026-08-24 02:42:29.376366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c3384772b5f'
down_revision: Union[str, Sequence[str], None] = '57c109e656c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_match', sa.Column('details_imported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_match', 'details_imported_at')
    # ### end Alembic commands ###
