"""add team match notice

Revision ID: 9258e60bfd1c
Revises: 9e7d37d5558d
Create Date: 2026-08-23 01:38:32.345068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9258e60bfd1c'
down_revision: Union[str, Sequence[str], None] = '9e7d37d5558d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teammatchnotice',
    sa.Column('team_match_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['team_match_id'], ['team_match.id'], ),
    sa.PrimaryKeyConstraint('team_match_id', 'code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teammatchnotice')
    # ### end Alembic commands ###
