"""initial schema

Revision ID: 9467ae3d6b41
Revises:
Create Date: 2026-08-28 04:25:47.320037

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9467ae3d6b41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("teaser", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "member",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("joined_at", sa.Date(), nullable=True),
        sa.Column("eligible_since", sa.Date(), nullable=True),
        sa.Column("ttc_eligible_since", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("membership_end_date", sa.Date(), nullable=True),
        sa.Column("phone", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mobile", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("street", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("house_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("postal_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=True)
    op.create_table(
        "season",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("end_year", sa.Integer(), nullable=False),
        sa.Column("half", sa.Enum("VR", "RR", name="seasonhalf"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "start_year", "end_year", "half", name="uq_season_years_half"
        ),
    )
    op.create_table(
        "league_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("mytt_group_id", sa.Integer(), nullable=False),
        sa.Column("mytt_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "season_id", "mytt_group_id", name="uq_league_group_season_mytt"
        ),
    )
    op.create_table(
        "player",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("mytt_person_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("nuid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id"),
    )
    op.create_index(
        op.f("ix_player_mytt_person_id"), "player", ["mytt_person_id"], unique=True
    )
    op.create_index(op.f("ix_player_nuid"), "player", ["nuid"], unique=True)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("password_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["member.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("member_id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "league_table_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league_group_id", sa.Integer(), nullable=False),
        sa.Column("mytt_team_id", sa.Integer(), nullable=False),
        sa.Column("club_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("meetings_count", sa.Integer(), nullable=False),
        sa.Column("meetings_won", sa.Integer(), nullable=False),
        sa.Column("meetings_tie", sa.Integer(), nullable=False),
        sa.Column("meetings_lost", sa.Integer(), nullable=False),
        sa.Column("points_won", sa.Integer(), nullable=False),
        sa.Column("points_lost", sa.Integer(), nullable=False),
        sa.Column("matches_won", sa.Integer(), nullable=False),
        sa.Column("matches_lost", sa.Integer(), nullable=False),
        sa.Column("sets_won", sa.Integer(), nullable=False),
        sa.Column("sets_lost", sa.Integer(), nullable=False),
        sa.Column("games_won", sa.Integer(), nullable=False),
        sa.Column("games_lost", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_group_id"],
            ["league_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "league_group_id", "mytt_team_id", name="uq_league_table_entry_group_team"
        ),
    )
    op.create_index(
        op.f("ix_league_table_entry_league_group_id"),
        "league_table_entry",
        ["league_group_id"],
        unique=False,
    )
    op.create_table(
        "player_rating",
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("qttr", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("player_id", "effective_date"),
    )
    op.create_table(
        "refreshsession",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("family_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refreshsession_expires_at"),
        "refreshsession",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refreshsession_family_id"),
        "refreshsession",
        ["family_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refreshsession_token_hash"),
        "refreshsession",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refreshsession_user_id"), "refreshsession", ["user_id"], unique=False
    )
    op.create_table(
        "team",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("league_group_id", sa.Integer(), nullable=False),
        sa.Column("mytt_team_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["league_group_id"],
            ["league_group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["season.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "mytt_team_id", name="uq_team_season_mytt"),
    )
    op.create_table(
        "userrolelink",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "team_assignment",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "player_id"),
    )
    op.create_table(
        "team_match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("mytt_meeting_id", sa.Integer(), nullable=True),
        sa.Column("opponent_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("play_mode", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("original_scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("venue_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("venue_street", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("venue_city", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("score_ttc", sa.Integer(), nullable=True),
        sa.Column("score_opponent", sa.Integer(), nullable=True),
        sa.Column("details_imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_match_is_completed"), "team_match", ["is_completed"], unique=False
    )
    op.create_index(
        op.f("ix_team_match_mytt_meeting_id"),
        "team_match",
        ["mytt_meeting_id"],
        unique=True,
    )
    op.create_table(
        "team_membership",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("rank", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["team.id"],
        ),
        sa.PrimaryKeyConstraint("team_id", "player_id"),
    )
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_match_id", sa.Integer(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "game_type", sa.Enum("SINGLE", "DOUBLE", name="gametype"), nullable=False
        ),
        sa.Column("match_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("mytt_match_uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_match_id"],
            ["team_match.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "team_match_id", "sequence", name="uq_match_team_match_sequence"
        ),
    )
    op.create_index(
        op.f("ix_match_mytt_match_uuid"), "match", ["mytt_match_uuid"], unique=True
    )
    op.create_table(
        "match_lineup",
        sa.Column("team_match_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("doubles_pair", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_match_id"],
            ["team_match.id"],
        ),
        sa.PrimaryKeyConstraint("team_match_id", "player_id"),
    )
    op.create_table(
        "team_match_notice",
        sa.Column("team_match_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=2), nullable=False),
        sa.Column("info", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_match_id"],
            ["team_match.id"],
        ),
        sa.PrimaryKeyConstraint("team_match_id", "code"),
    )
    op.create_table(
        "match_participant",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("opponent_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "player_id"),
    )
    op.create_table(
        "set_result",
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("set_number", sa.Integer(), nullable=False),
        sa.Column("points_ttc", sa.Integer(), nullable=False),
        sa.Column("points_opponent", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
        ),
        sa.PrimaryKeyConstraint("match_id", "set_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("set_result")
    op.drop_table("match_participant")
    op.drop_table("team_match_notice")
    op.drop_table("match_lineup")
    op.drop_index(op.f("ix_match_mytt_match_uuid"), table_name="match")
    op.drop_table("match")
    op.drop_table("team_membership")
    op.drop_index(op.f("ix_team_match_mytt_meeting_id"), table_name="team_match")
    op.drop_index(op.f("ix_team_match_is_completed"), table_name="team_match")
    op.drop_table("team_match")
    op.drop_table("team_assignment")
    op.drop_table("userrolelink")
    op.drop_table("team")
    op.drop_index(op.f("ix_refreshsession_user_id"), table_name="refreshsession")
    op.drop_index(op.f("ix_refreshsession_token_hash"), table_name="refreshsession")
    op.drop_index(op.f("ix_refreshsession_family_id"), table_name="refreshsession")
    op.drop_index(op.f("ix_refreshsession_expires_at"), table_name="refreshsession")
    op.drop_table("refreshsession")
    op.drop_table("player_rating")
    op.drop_index(
        op.f("ix_league_table_entry_league_group_id"), table_name="league_table_entry"
    )
    op.drop_table("league_table_entry")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_player_nuid"), table_name="player")
    op.drop_index(op.f("ix_player_mytt_person_id"), table_name="player")
    op.drop_table("player")
    op.drop_table("league_group")
    op.drop_table("season")
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.drop_table("role")
    op.drop_table("member")
    op.drop_table("article")

    op.execute("DROP TYPE IF EXISTS gametype")
    op.execute("DROP TYPE IF EXISTS seasonhalf")
    # ### end Alembic commands ###
