"""link user to member

Revision ID: 9e7d37d5558d
Revises: 78462def9f67
Create Date: 2026-08-21 15:26:39.359806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7d37d5558d'
down_revision: Union[str, Sequence[str], None] = '78462def9f67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('member_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['member_id'])
    op.create_foreign_key(None, 'user', 'member', ['member_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'member_id')
    # ### end Alembic commands ###
