"""add league table

Revision ID: bfa66fc8f888
Revises: e47ba3f045af
Create Date: 2026-08-27 01:59:24.789101

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfa66fc8f888"
down_revision: Union[str, Sequence[str], None] = "e47ba3f045af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "league_table_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("league_group_id", sa.Integer(), nullable=False),
        sa.Column("mytt_team_id", sa.Integer(), nullable=False),
        sa.Column("club_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("team_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("meetings_count", sa.Integer(), nullable=False),
        sa.Column("meetings_won", sa.Integer(), nullable=False),
        sa.Column("meetings_tie", sa.Integer(), nullable=False),
        sa.Column("meetings_lost", sa.Integer(), nullable=False),
        sa.Column("points_won", sa.Integer(), nullable=False),
        sa.Column("points_lost", sa.Integer(), nullable=False),
        sa.Column("matches_won", sa.Integer(), nullable=False),
        sa.Column("matches_lost", sa.Integer(), nullable=False),
        sa.Column("sets_won", sa.Integer(), nullable=False),
        sa.Column("sets_lost", sa.Integer(), nullable=False),
        sa.Column("games_won", sa.Integer(), nullable=False),
        sa.Column("games_lost", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_group_id"],
            ["league_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "league_group_id", "mytt_team_id", name="uq_league_table_entry_group_team"
        ),
    )
    op.create_index(
        op.f("ix_league_table_entry_league_group_id"),
        "league_table_entry",
        ["league_group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_league_table_entry_league_group_id"), table_name="league_table_entry"
    )
    op.drop_table("league_table_entry")
    # ### end Alembic commands ###
