"""add match metadata and play mode 2

Revision ID: e47ba3f045af
Revises: 64f466877dae
Create Date: 2026-08-26 01:24:13.636500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e47ba3f045af'
down_revision: Union[str, Sequence[str], None] = '64f466877dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('match_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('match', sa.Column('mytt_match_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_match_mytt_match_uuid'), 'match', ['mytt_match_uuid'], unique=True)
    op.add_column('team_match', sa.Column('play_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_match', 'play_mode')
    op.drop_index(op.f('ix_match_mytt_match_uuid'), table_name='match')
    op.drop_column('match', 'mytt_match_uuid')
    op.drop_column('match', 'match_name')
    # ### end Alembic commands ###
