from typing import Protocol, Self

from app.core.users.application.dto import UserCredentials, UserDetails
from app.core.users.domain.user import Role, User


class UserRepository(Protocol):
    def get(self, user_id: int) -> User | None: ...
    def email_exists(self, email: str) -> bool: ...
    def save(self, user: User) -> User: ...


class RoleRepository(Protocol):
    def get_by_name(self, name: str) -> Role | None: ...
    def add(self, name: str) -> None: ...


class UserUnitOfWork(Protocol):
    users: UserRepository
    roles: RoleRepository

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...


class Passwords(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class UserReader(Protocol):
    """Supported read contract for Auth and editorial projections."""

    def get_public(self, user_id: int) -> UserDetails | None: ...
    def get_credentials(self, email: str) -> UserCredentials | None: ...
    def get_names(self, user_ids: set[int]) -> dict[int, str]: ...
    def get_system_author_id(self) -> int | None: ...
