from datetime import datetime
from typing import Protocol, Self

from app.core.members.public import Member, Members
from app.core.users.application.dto import (
    ListUsersQuery,
    ManagedUser,
    MemberOption,
    UserCredentials,
    UserDetails,
    UserPage,
)
from app.core.users.domain.password_link import PasswordLink
from app.core.users.domain.user import Role, User


class UserRepository(Protocol):
    def get(self, user_id: int) -> User | None: ...
    def email_exists(self, email: str) -> bool: ...
    def save(self, user: User) -> User: ...
    def lock_administration(self) -> None: ...
    def active_admin_count(self) -> int: ...
    def member_in_use(self, member_id: int, user_id: int | None) -> bool: ...
    def delete(self, user: User) -> None: ...


class PasswordLinks(Protocol):
    def replace(self, link: PasswordLink) -> None: ...
    def get(self, token_hash: str) -> PasswordLink | None: ...
    def delete_for_user(self, user_id: int) -> None: ...


class AccountSessions(Protocol):
    def revoke(self, user_id: int, now: datetime) -> None: ...
    def delete(self, user_id: int) -> None: ...


class PasswordLinkTokens(Protocol):
    def create(self) -> str: ...
    def digest(self, token: str) -> str: ...


class PasswordMail(Protocol):
    def ensure_configured(self) -> None: ...
    def send(self, email: str, token: str) -> None: ...


class RoleRepository(Protocol):
    def get_by_name(self, name: str) -> Role | None: ...
    def add(self, name: str) -> None: ...


class UserUnitOfWork(Protocol):
    users: UserRepository
    roles: RoleRepository
    members: Members
    links: PasswordLinks
    sessions: AccountSessions

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...


class Passwords(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class UserReader(Protocol):
    """Supported read contract for Auth and editorial projections."""

    def get_public(self, user_id: int) -> UserDetails | None: ...
    def get_credentials(self, email: str) -> UserCredentials | None: ...
    def get_names(self, user_ids: set[int]) -> dict[int, str]: ...
    def get_system_author_id(self) -> int | None: ...


class UserAdministrationReader(Protocol):
    def list_users(self, query: ListUsersQuery) -> UserPage: ...
    def get_user(self, user_id: int) -> ManagedUser | None: ...
    def member_options(self) -> list[MemberOption]: ...
    def get_member(self, member_id: int) -> Member | None: ...
