from datetime import datetime
from typing import Protocol, Self

from app.core.competition.application.sync.automation.dto import SyncMatchOverview
from app.core.competition.application.sync.commands import (
    SyncMeeting,
    SyncRegistrations,
    SyncSchedule,
    SyncStandings,
)
from app.core.competition.domain.match_reload import MatchReload, ReloadTarget
from app.core.competition.domain.sync_automation import (
    ScheduledMatch,
    SyncSettings,
    SyncState,
)


class AutomationRepository(Protocol):
    def settings(self) -> SyncSettings: ...
    def save_settings(self, settings: SyncSettings) -> None: ...
    def state(self) -> SyncState: ...
    def save_state(self, state: SyncState) -> None: ...
    def heartbeat(self) -> datetime | None: ...
    def save_heartbeat(self, now: datetime) -> None: ...
    def candidates(self, since: datetime) -> list[ScheduledMatch]: ...
    def attempted(self, match: ScheduledMatch, now: datetime) -> None: ...
    def reload_target(self, match_id: int) -> ReloadTarget | None: ...
    def reload_request(self, match_id: int) -> MatchReload | None: ...
    def save_reload(self, request: MatchReload) -> None: ...
    def next_reload(self) -> MatchReload | None: ...
    def running_reloads(self) -> list[MatchReload]: ...


class SyncMatchOverviewReader(Protocol):
    def read(self, now: datetime) -> SyncMatchOverview: ...


class AutomationUnitOfWork(Protocol):
    repository: AutomationRepository

    def __enter__(self) -> Self: ...
    def __exit__(self, *args) -> None: ...
    def commit(self) -> None: ...


class ScheduledCompetition(Protocol):
    schedule: SyncSchedule
    meeting: SyncMeeting
    standings: SyncStandings
    registrations: SyncRegistrations
