from datetime import datetime
from typing import Protocol, Self
from uuid import UUID

from app.core.auth.domain.session import RefreshSession


class RefreshSessionRepository(Protocol):
    def get_for_update(self, token_hash: str) -> RefreshSession | None: ...
    def save(self, session: RefreshSession) -> None: ...
    def revoke_family(self, family_id: UUID, now: datetime) -> None: ...


class AuthUnitOfWork(Protocol):
    sessions: RefreshSessionRepository

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_value, traceback) -> None: ...
    def commit(self) -> None: ...


class Tokens(Protocol):
    def issue_access(self, user_id: int, now: datetime) -> str: ...
    def decode_access(self, token: str) -> int | None: ...
    def issued_after(self, token: str, cutoff: datetime) -> bool: ...
    def new_refresh(self) -> str: ...
    def hash_refresh(self, token: str) -> str: ...
